name = "limitlessweb-pages"
compatibility_date = "2024-10-01"

[vars]
# ADMIN_USER="admin"
# ADMIN_PASS="super-secure-password"
# SESSION_SECRET="random-long-secret"

[[d1_databases]]
binding = "DB"
database_name = "limitlessweb"
database_id = "REPLACE_WITH_YOUR_D1_DB_ID"
